"""empty message

Revision ID: 610ce4744e65
Revises: 2522715c52fb
Create Date: 2021-08-31 17:14:15.372176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610ce4744e65'
down_revision = '2522715c52fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusterfee',
    sa.Column('cluster', sa.Integer(), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('cluster')
    )
    op.create_index(op.f('ix_clusterfee_fee'), 'clusterfee', ['fee'], unique=False)
    op.drop_index('ix_cluster_fee_cluster', table_name='cluster_fee')
    op.drop_index('ix_cluster_fee_fee', table_name='cluster_fee')
    op.drop_index('ix_cluster_fee_year', table_name='cluster_fee')
    op.drop_table('cluster_fee')
    op.add_column('unit', sa.Column('dom_cl', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'unit', 'clusterfee', ['dom_cl'], ['cluster'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit', type_='foreignkey')
    op.drop_column('unit', 'dom_cl')
    op.create_table('cluster_fee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.VARCHAR(length=64), nullable=True),
    sa.Column('cluster', sa.INTEGER(), nullable=True),
    sa.Column('fee', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cluster_fee_year', 'cluster_fee', ['year'], unique=False)
    op.create_index('ix_cluster_fee_fee', 'cluster_fee', ['fee'], unique=False)
    op.create_index('ix_cluster_fee_cluster', 'cluster_fee', ['cluster'], unique=False)
    op.drop_index(op.f('ix_clusterfee_fee'), table_name='clusterfee')
    op.drop_table('clusterfee')
    # ### end Alembic commands ###
