"""new schema

Revision ID: ab45049ab297
Revises: 9f362f4c7a2d
Create Date: 2021-09-09 17:49:42.979249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab45049ab297'
down_revision = '9f362f4c7a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_name',
    sa.Column('course_code', sa.String(length=64), nullable=False),
    sa.Column('course_name', sa.String(length=64), nullable=True),
    sa.Column('course_fee', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('course_code')
    )
    op.create_index(op.f('ix_course_name_course_fee'), 'course_name', ['course_fee'], unique=False)
    op.create_index(op.f('ix_course_name_course_name'), 'course_name', ['course_name'], unique=False)
    op.create_table('student_type',
    sa.Column('level', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('level', 'location')
    )
    op.create_table('unit_fee',
    sa.Column('unit_code', sa.String(length=64), nullable=False),
    sa.Column('unit_fee', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('unit_code')
    )
    op.create_index(op.f('ix_unit_fee_unit_fee'), 'unit_fee', ['unit_fee'], unique=False)
    op.create_table('dropdowns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('course_code', sa.String(length=64), nullable=True),
    sa.Column('years', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_code'], ['course_name.course_code'], ),
    sa.ForeignKeyConstraint(['level'], ['student_type.level'], ),
    sa.ForeignKeyConstraint(['location'], ['student_type.location'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dropdowns_years'), 'dropdowns', ['years'], unique=False)
    op.drop_index('ix_cluster_fee_fee', table_name='cluster_fee')
    op.drop_table('cluster_fee')
    op.drop_index('ix_courses_course_code', table_name='courses')
    op.drop_table('courses')
    op.drop_table('course_fees')
    op.drop_index('ix_study_abroad_fees_course_code', table_name='study_abroad_fees')
    op.drop_index('ix_study_abroad_fees_fee_type_code', table_name='study_abroad_fees')
    op.drop_table('study_abroad_fees')
    op.drop_index('ix_course_fee_types_course_code', table_name='course_fee_types')
    op.drop_index('ix_course_fee_types_fee_type_code', table_name='course_fee_types')
    op.drop_table('course_fee_types')
    op.drop_index('ix_unit_title', table_name='unit')
    op.drop_index('ix_unit_unit_cd', table_name='unit')
    op.drop_table('unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('unit_cd', sa.VARCHAR(length=64), nullable=True),
    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.Column('points', sa.INTEGER(), nullable=True),
    sa.Column('foe', sa.INTEGER(), nullable=True),
    sa.Column('dom_cl', sa.INTEGER(), nullable=True),
    sa.Column('no_award_cl', sa.INTEGER(), nullable=True),
    sa.Column('inter_cl', sa.INTEGER(), nullable=True),
    sa.Column('census_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['dom_cl'], ['cluster_fee.cluster'], ),
    sa.ForeignKeyConstraint(['inter_cl'], ['cluster_fee.cluster'], ),
    sa.ForeignKeyConstraint(['no_award_cl'], ['cluster_fee.cluster'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_unit_unit_cd', 'unit', ['unit_cd'], unique=False)
    op.create_index('ix_unit_title', 'unit', ['title'], unique=False)
    op.create_table('course_fee_types',
    sa.Column('course_code', sa.INTEGER(), nullable=False),
    sa.Column('fee_type_code', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('course_code', 'fee_type_code')
    )
    op.create_index('ix_course_fee_types_fee_type_code', 'course_fee_types', ['fee_type_code'], unique=False)
    op.create_index('ix_course_fee_types_course_code', 'course_fee_types', ['course_code'], unique=False)
    op.create_table('study_abroad_fees',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fee_type_code', sa.INTEGER(), nullable=True),
    sa.Column('course_code', sa.INTEGER(), nullable=True),
    sa.Column('course_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('fee', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_study_abroad_fees_fee_type_code', 'study_abroad_fees', ['fee_type_code'], unique=False)
    op.create_index('ix_study_abroad_fees_course_code', 'study_abroad_fees', ['course_code'], unique=False)
    op.create_table('course_fees',
    sa.Column('fee_type_code', sa.INTEGER(), nullable=False),
    sa.Column('course_code', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('fee', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('fee_type_code', 'course_code')
    )
    op.create_table('courses',
    sa.Column('course_code', sa.INTEGER(), nullable=False),
    sa.Column('course_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.Column('credit', sa.INTEGER(), nullable=True),
    sa.Column('req_credit', sa.INTEGER(), nullable=True),
    sa.Column('ctc', sa.INTEGER(), nullable=True),
    sa.Column('broad_ctc', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('course_code'),
    sa.UniqueConstraint('course_name')
    )
    op.create_index('ix_courses_course_code', 'courses', ['course_code'], unique=False)
    op.create_table('cluster_fee',
    sa.Column('year', sa.VARCHAR(length=64), nullable=False),
    sa.Column('cluster', sa.INTEGER(), nullable=False),
    sa.Column('fee', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('year', 'cluster')
    )
    op.create_index('ix_cluster_fee_fee', 'cluster_fee', ['fee'], unique=False)
    op.drop_index(op.f('ix_dropdowns_years'), table_name='dropdowns')
    op.drop_table('dropdowns')
    op.drop_index(op.f('ix_unit_fee_unit_fee'), table_name='unit_fee')
    op.drop_table('unit_fee')
    op.drop_table('student_type')
    op.drop_index(op.f('ix_course_name_course_name'), table_name='course_name')
    op.drop_index(op.f('ix_course_name_course_fee'), table_name='course_name')
    op.drop_table('course_name')
    # ### end Alembic commands ###
